name: "Build go binary"
on:
  workflow_dispatch: {}
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: "./src"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16' # The Go version to download (if necessary) and use.
      - name: Build
        run: go build
      - name: ls
        run: ls
