name: "Build go binary"
on:
  workflow_dispatch: {}
  push:
    branches:
      - "master"
      - "workflow-build"  # TODO Remove before merge

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16' # The Go version to download (if necessary) and use.
      - name: Change directory
        run: cd ./src
      - name: ls
        run: ls
      - name: Build
        working-directory: ./src
        run: go build
      - name: ls
        run: ls
