name: Build, Test & Push
on:
  workflow_dispatch: {}
  push:
    branches:
      - '**'  # all branches

jobs:
  buildTestPush:
    name: Build, Test & Push
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      # Build
      - name: Docker cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Docker build
        run: docker build . -t ir2mqtt

      # Test
      - name: (test) Start container
        run: docker run --rm -d --name=ir2mqtt --net=host ir2mqtt
      - name: (test) Wait for port
        uses: nev7n/wait_for_response@v1
        with:
          url: "http://localhost:8420"
          responseCode: 200
          timeout: 15000
          interval: 200
      - name: (test) Access the frontend
        run: curl -f http://localhost:8420
